server:
  port: 9999

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/marimo
    username: ohgiraffers
    password: ohgiraffers
  config:
    import: "file:./.env"

  jpa:
    show-sql: true # SQL 쿼리 로깅 활성화. 실행되는 모든 SQL 쿼리를 콘솔에 출력함.
    database: mysql # JPA가 사용할 데이터베이스 타입 설정. 여기서는 MySQL을 지정함.
    hibernate:
      ddl-auto: update # 데이터베이스 스키마 자동 업데이트. 엔티티 클래스 변경 시 DB 스키마를 자동으로 수정해줌.
    properties:
      hibernate:
        format_sql: true # SQL 쿼리 로깅 시 출력되는 SQL을 읽기 쉽게 포맷팅함.
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB # 파일 업로드 제한 용량
      max-request-size: 10MB # 파일 응답 제한 용량

external:
  api:
    hot-sitting-server-url: ${AI_HOT_SITTING_SERVER_URL}
    avatar-server-url: ${AI_AVATAR_SERVER_URL}
    background-server-url: ${AI_BACKGROUND_SERVER_URL}
    lesson-material-server-url: ${AI_LESSON_MATERIAL_SERVER_URL}
